In [34]:
import pickle
import numpy as np


In [35]:
ohe_sex=pickle.load(open('/content/ohe_sex (1).pkl','rb'))
ohe_embarked=pickle.load(open('/content/ohe_embarked (1).pkl','rb'))
model=pickle.load(open('/content/clf (2).pkl','rb'))

In [36]:
# assume user input
# pclass/ gender/ age/sibsp/fare/Embarked
test_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [37]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [42]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1)).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [43]:
test_input_sex

array([[0., 1.]])

In [47]:
test_input_embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1)).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [48]:
test_input_embarked

array([[0., 0., 1., 0.]])

In [49]:
test_input_age=test_input[:,2].reshape(1,1)

In [50]:
test_input_transformed=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [52]:
test_input_transformed.shape

(1, 11)

In [56]:
clf.predict(test_input_transformed)

array([1])